### ISSUE TITLE
Feature: User can search for a team/player.

### ISSUE THREAD

**Issue by TreMitchell** [TreMitchell/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

"Users can search for a player and a team."

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
"Users want to keep track of their favorite players or teams to see how they are performing during the NBA season. This function is to help users stay alert on what  their favorite players and/or teams are doing during the NBA season."

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="751" alt="Screenshot 2024-10-08 at 9 25 16 AM" src="https://github.com/user-attachments/assets/3d98219c-60dc-4e51-bae7-67ec15713fb2">
<img width="754" alt="Screenshot 2024-10-08 at 9 25 35 AM" src="https://github.com/user-attachments/assets/890bd6c0-7132-4293-970d-9e9a1b0ad97b">
<img width="753" alt="Screenshot 2024-10-08 at 9 25 44 AM" src="https://github.com/user-attachments/assets/266994f1-b779-4b15-913e-223761362099">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] *Create a navbar that includes four tabs to choose from: players, teams, schedule, and standings* 
- [x] Create a search feature that consists of the search bar and search button to be able to search for a player/team.
- [x] Create a results display that shows the results of the player/team that the user searched for.
- [x] Use the NBA API to store the storage.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
